name: x_chaos_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - aiofiles==25.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.0
    - apache-beam==2.69.0
    - asciitree==0.3.3
    - asn1crypto==1.5.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - backports-tarfile==1.2.0
    - beartype==0.21.0
    - cachetools==6.2.2
    - certifi==2025.11.12
    - cffi==2.0.0
    - cftime==1.6.5
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloud-sql-python-connector==1.18.5
    - cloudpickle==3.1.2
    - crcmod==1.7
    - cryptography==46.0.3
    - dask==2025.11.0
    - decorator==5.2.1
    - dnspython==2.8.0
    - docopt==0.6.2
    - docstring-parser==0.17.0
    - exceptiongroup==1.3.1
    - fastavro==1.12.1
    - fasteners==0.20
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - gcsfs==2025.10.0
    - google-api-core==2.28.1
    - google-apitools==0.5.31
    - google-auth==2.41.1
    - google-auth-httplib2==0.2.1
    - google-auth-oauthlib==1.2.3
    - google-cloud-aiplatform==1.129.0
    - google-cloud-bigquery==3.38.0
    - google-cloud-bigquery-storage==2.34.0
    - google-cloud-bigtable==2.34.0
    - google-cloud-core==2.5.0
    - google-cloud-datastore==2.21.0
    - google-cloud-dlp==3.33.0
    - google-cloud-language==2.18.0
    - google-cloud-pubsub==2.33.0
    - google-cloud-pubsublite==1.12.0
    - google-cloud-recommendations-ai==0.10.18
    - google-cloud-resource-manager==1.15.0
    - google-cloud-secret-manager==2.25.0
    - google-cloud-spanner==3.59.0
    - google-cloud-storage==2.19.0
    - google-cloud-videointelligence==2.17.0
    - google-cloud-vision==3.11.0
    - google-crc32c==1.7.1
    - google-genai==1.52.0
    - google-resumable-media==2.8.0
    - googleapis-common-protos==1.72.0
    - grpc-google-iam-v1==0.14.3
    - grpc-interceptor==0.15.4
    - grpcio==1.65.5
    - grpcio-status==1.65.5
    - h11==0.16.0
    - hdfs==2.7.3
    - httpcore==1.0.9
    - httplib2==0.22.0
    - httpx==0.28.1
    - idna==3.11
    - immutabledict==4.2.2
    - importlib-metadata==8.7.0
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - jax==0.6.2
    - jaxlib==0.6.2
    - jeepney==0.9.0
    - joblib==1.5.2
    - jsonpickle==3.4.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - keyring==25.7.0
    - keyrings-google-artifactregistry-auth==1.1.2
    - locket==1.0.0
    - ml-dtypes==0.5.4
    - more-itertools==10.8.0
    - multidict==6.7.0
    - numcodecs==0.13.1
    - numpy==2.2.6
    - oauth2client==4.1.3
    - oauthlib==3.3.1
    - objsize==0.7.1
    - opentelemetry-api==1.38.0
    - opentelemetry-sdk==1.38.0
    - opentelemetry-semantic-conventions==0.59b0
    - opt-einsum==3.4.0
    - orjson==3.11.4
    - overrides==7.7.0
    - packaging==25.0
    - pandas==2.3.3
    - partd==1.4.2
    - pg8000==1.31.5
    - pluggy==1.6.0
    - propcache==0.4.1
    - proto-plus==1.26.1
    - protobuf==5.29.5
    - pyarrow==18.1.0
    - pyarrow-hotfix==0.7
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycparser==2.23
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydot==1.4.2
    - pyjwt==2.10.1
    - pymongo==4.15.5
    - pymysql==1.1.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-tds==1.17.1
    - pytz==2025.2
    - pyyaml==6.0.3
    - redis==5.3.1
    - referencing==0.37.0
    - regex==2025.11.3
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rpds-py==0.30.0
    - rsa==4.9.1
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - scramp==1.4.6
    - secretstorage==3.5.0
    - shapely==2.1.2
    - six==1.17.0
    - sortedcontainers==2.4.0
    - sqlparse==0.5.4
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - toolz==1.1.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - weatherbench2==0.2.1
    - websockets==15.0.1
    - xarray==2025.6.1
    - xarray-beam==0.11.5
    - yarl==1.22.0
    - zarr==2.18.3
    - zipp==3.23.0
    - zstandard==0.25.0
prefix: /usr/users/x_chaos_meteo/arfib_lou/.conda/envs/x_chaos_env
